### ISSUE TITLE
Weird Error with Luckperms

### ISSUE THREAD

**Issue by nicholasveronico** [MrTigreroux/TigerReports#114]
Hey again!

This error comes up whenever doing /reports on my hub servers. No reports or archived reports are loaded in the GUI due to this. 

https://www.toptal.com/developers/hastebin/geyuwolibi.sql

**Comment by MrTigreroux** [comment]
Hi,

Could you check in the logs before that error if the player Paffz was connected and just disconnected before the error happens ?

**Comment by nicholasveronico** [comment]
The error occurred whenever I initiated the reports command. The player in question was not online on the hub server at the time.

If it helps, that player used to be staff on the network a few months ago but has since resigned.

**Comment by MrTigreroux** [comment]
Ok but when was this player online (on that specific Spigot server, not on your network) for the last time before this error happened ? (You normally can see his connection and disconnection in the logs by searching for his UUID).
I partially found the source of the problem, but the error you have reveals that the disconnection of that player wasn't correctly processed.

**Comment by nicholasveronico** [comment]
The player never logged on to that specific spigot server. I don't think the error occurred when they logged on or left. I only noticed it when I used the /reports command

**Comment by MrTigreroux** [comment]
If you installed the last version 5.0.14 of TigerReports, you must have restarted your Spigot server. In that version, an OnlineUserData instance is only created if the player is online (on the Spigot server, not on the BungeeCord network). I checked again but if the player was never connected on that Spigot server, there could not be any OnlineUserData for him (there could have an error but that OnlineUserData would not exist).
You cannot have an OnlineUserData instance for a player that never joined the Spigot server since you restarted your server with the last version 5.0.14.
I don't know how you checked, but I think you made a mistake writting the UUID '33c02316-f7fd-4204-8178-e6a4f0ea9ffa' and searching for it in the logs.
I really need to know how many times this player joined and leaved that Spigot server before the error happened, with the timestamp.

**Comment by nicholasveronico** [comment]
Apologies. I was looking at another log with the same error but a different player. Here is a full log of a different UUID but the same error.

https://mcpaste.io/ba81896bcf7818e0

**Comment by nicholasveronico** [comment]
Not related, but this error also just came up: https://www.toptal.com/developers/hastebin/ekemihucok.properties

**Comment by MrTigreroux** [comment]
I think that the first error you have will be fixed in the new [version 5.0.15](https://www.spigotmc.org/resources/tigerreports.25773/update?update=456329). Let me know if it's not the case.

**Comment by MrTigreroux** [comment]
> For the second error, the "archived" column of the "tigerreports_reports" table is already INT(1).

Ok... Then try with 'INT(2)'.

**Comment by nicholasveronico** [comment]
I think 'INT(2)' fixed the issue. Thanks!

**Comment by nicholasveronico** [comment]
This is unrelated, again, but I noticed this on my timings report. 

https://imgur.com/a/qhHUifX

**Comment by MrTigreroux** [comment]
The timings you see correspond to the Web request to the SpigotMC API to check if a new version of TigerReports is available.
I see "count(2)", so I assume you use TigerReportsSupports.
This web request is made only once, after each load (start of the plugin or reload), and in an asynchronous task (to don't freeze the server). I don't know why you see such timings, but I guess the "Minecraft:Bukkit Scheduler" confirms that this "bad timing" doesn't impact the in game performance because it is not done on the server main thread.
