### ISSUE TITLE
Lag issues when MySQL is enabled

### ISSUE THREAD

**Issue by PanGargamel** [MrTigreroux/TigerReports#12]
I am experiencing lag issues when MySQL database is enabled.
It looks like the plugin is not running MySQL queries asynchronously, but on the main thread.
When an user reports someone, the server is freezed for a few seconds. The same happens when an administrator selects any report in /reports GUI. I also noticed that this happens especially if the /report (or /reports) command hasn't been used for a long time before.

Server version: git-Paper-176 (MC: 1.14.4)
Plugin version: 4.9.1
The MySQL database is not running on localhost, but on a different, external server.

**Comment by MrTigreroux** [comment]
I'm sorry but I don't think I can fix this.
I try to run asynchronously as queries as possible but you are invoking situations where the database must answer to accomplish the action (when reporting a player, the plugin needs to check that the report isn't refused by the database, when opening the menu of a report, the data of the report must be collected, ...). Maybe you would consider to change your database because the "lag" aren't really significant when I personnaly test it with a free online MySQL database.

**Comment by PanGargamel** [comment]
I just created a pull request with async /report command - I'm not actually regularly writing any plugins for Minecraft servers, so I would like to ask you for a review. As for me, it looks like it works well - DB queries are made asynchronously and I haven't encountered any new problems.

**Comment by MrTigreroux** [comment]
Effectively it seems to work. I didn't think about it because I thought messages sent asynchronously would induce problems but I was wrong.
I don't really know how to use GitHub branch feature properly so I will not use your pull request directly but thank you for the help, I add your changes in the next version.

**Comment by PanGargamel** [comment]
Thanks for adding my changes!
I will look into the menus in the next days and give a reply here if I find any solution. TigerReports is the best report-management plugin I found, so I would be glad to help you.

**Comment by PanGargamel** [comment]
Okay, it didn't take so long.
I just implemented async menu loading in #15 pull request, please check it out and see if there's anything wrong.

**Comment by PanGargamel** [comment]
Just checked my implementation with ~50 players online and it looks like the lag is still present. Will come back with the solution later.

**Comment by MrTigreroux** [comment]
Yes, you put the statistics query asynchronous but the report query remains sync (in [ReportManagerMenu](https://github.com/PanGargamel/TigerReports/blob/e1ef055b2c0a383e1413445777dfec80ad3b8418/TigerReports/src/fr/mrtigreroux/tigerreports/objects/menus/ReportManagerMenu.java#L20) class).

**Comment by PanGargamel** [comment]
I just updated #15 - now it looks like the only problem that is causing lags is loading player's skulls in GUI. I'll try to fix that tomorrow probably.

**Comment by MrTigreroux** [comment]
Thank you again for the help, I made your changes but a little differently to keep updating the report when opening a new menu (you are keeping the same (potentialy unupdated) report across the menus).
I will update the plugin tomorrow.

**Comment by MrTigreroux** [comment]
I implemented asynchronous process for database queries in the new [version 4.9.4](https://www.spigotmc.org/resources/tigerreports.25773/update?update=297220). Thank you again for the help.

**Comment by PanGargamel** [comment]
Thanks! I think the issue should be closed now :)
