### ISSUE TITLE
Teleportation and loading of reports

### ISSUE THREAD

**Issue by DanRubMaster** [MrTigreroux/TigerReports#144]
**_Hello_**, I have questions again that I don't know how to solve.
**1.** [HERE](https://youtu.be/nBHK8PirVJ0) you can see that when the report is on another server and I want to teleport to that server through the report menu, it first throws me to the spawn lobby and only after 2 seconds it ports me to that player, is there a fix for that, because it's quite annoying.

**2.** [HERE](https://youtu.be/JlKS3NgqBys) you can see that if I have an account on the other's server and I want to port to the player again, it ports the other's account and not me, that's not such a big problem, but rather if it can be solved somehow, because I don't understand what it is..

**3.** [HERE](https://ibb.co/SxhPV73) and [HERE](https://ibb.co/6sVX0Wz) you can see that regarding the skins, when I'm on the server where both reportnut people are, the skins are loaded, but when I'm on another server, for some reason only one is loaded, I don't know why..

**4.** Finally, I wanted to ask if there is any way to speed up the loading of those reports and skins and the like, because it always takes about a second, which is simply annoying when all other plugins run without delay.

Thank you for your time.

**Comment by MrTigreroux** [comment]
Hello,
1. I will see how I can reduce this time, thank you for reporting it. 
2. I'm sorry I don't understand.
3. I think you are on a cracked server, so the skins cannot be loaded when the user is not on the same server, since the skin depends on your server.
4. You can only compare TigerReports to another plugin that displays live data of a database. Comparing it with any other type of plugin is nonsense.
Performances is something difficult to improve, because it depends on a lot of things: the communication between your database and your Spigot server (are they installed on the same machine ?), the communication between you and your Spigot server, the amount of plugins, average TPS, amount of players, activity of other plugins (for example executing a big WorldEdit operation will induce bad performances....) of your Spigot server.
There is a "timings" feature in Spigot that allows to monitor time execution of plugins, try to run it to see if there is any other plugin that uses too much of your server resources. Try also to remove all other plugins, keep only TigerReports, and see if the performances are better or not for displaying the reports.

**Comment by MrTigreroux** [comment]
Hello, you can now reduce the time when teleporting in the new [version 5.3](https://www.spigotmc.org/resources/tigerreports.25773/update?update=526401). Have a good day.
