### ISSUE TITLE
It is impossible to report a player

### ISSUE THREAD

**Issue by Andrey-skript** [MrTigreroux/TigerReports#154]
Hello!
I had a problem when I wrote /report  nickname my says that I can’t file a complaint against a player although he doesn’t even have rights to /reports

**Comment by MrTigreroux** [comment]
Hello,
I'm sorry I don't understand. By nickname are you referring to the name of a player or the his nickname from a nick plugin ?
What command did you exactly type please ?
Can I see a screenshot of the message you get please ?
What permissions of TigerReports does this player and you have ?

**Comment by Andrey-skript** [comment]
![image](https://github.com/MrTigreroux/TigerReports/assets/149084720/83231257-ccff-4349-833a-75d89ef23de1)
1. Nickname player
2. /report nickname
3. tigerreports.report

**Comment by MrTigreroux** [comment]
1. I don't understand.
2. That's not the exact command you typed.
3. I assume you both have the same unique `tigerreports.report` permission. Try again today and it should work (because probably that player Nagibator2001 had the `tigerreports.report.exempt` permission but you removed it but this player needs to log out then log in again to update its permission when you have a BungeeCord network).
If it's still not working, what permissions plugin do you use, are you sure this player hasn't a permission group giving him the `tigerreports.report.exempt` permission ?

**Comment by Andrey-skript** [comment]
1. LuckPerms
2. No
3. I fixed the error, it was due to a configuration breakdown

**Comment by MrTigreroux** [comment]
Ok, have a good day
