### ISSUE TITLE
add a check_update_notify = false or disabled update notify permission node

### ISSUE THREAD

**Issue by Shizoukia** [MrTigreroux/TigerReports#159]
Hello, I have had a great experience using this plugin on my server
But I would like to request the addition of a permission node/switch to prompt administrator users for plugin updates? Because my server does not require frequent updates of plugins and there are too many changes required to update plugins (based on Bungerecord's multiple sub servers), but this message often reminds administrators to request updates. I hope to turn off this prompt

My English is not very good. This is translated by a google. Please understand
Have a good day :D

**Comment by MrTigreroux** [comment]
Hello, I'm happy to know you like the plugin.
I'm not fan of encouraging people not to update the plugin, but I can understand that the notification can be annoying and since the plugin is relatively stable now, I will add a setting to disable the updates notifications.
Thank you for the suggestion, have a good day.

**Comment by MrTigreroux** [comment]
Hello, I just added a way to disable new version check in the new [version 5.3.4](https://www.spigotmc.org/resources/tigerreports.25773/update?update=553487). Thank you again and have a good day.
