### ISSUE TITLE
Config editing variability

### ISSUE THREAD

**Issue by Greyfuurt** [MrTigreroux/TigerReports#167]
The plugin is great, but it would be much better if we could change the type and location of items in the menu, and even add custom model data to those items and edit the menu names. For example, I really want to use this plugin to decorate with special textures, but the plugin does not allow this.

**Comment by MrTigreroux** [comment]
Hello, the more configuration options you have, the poorer the server performance, and the harder it is to maintain (update/fix/improve). Everything has a cost. Since what really matters is the accessibility of the features, I chose to allow the plugin to be fully translatable, but I didn't allowed the customization of the position/look of buttons that is not really necessary from my point of view.
I hope you can understand it.
