### ISSUE TITLE
Add option to disable skulls in GUI

### ISSUE THREAD

**Issue by PanGargamel** [MrTigreroux/TigerReports#19]
Some time ago I've suggested to make TigerReports more asynchronous which was successfully implemented. Anyway, there's still one problem as I mentioned earlier - the skulls. As for now, I don't have time to work on loading them async, but there could be an option in config just to replace them with simple Steve skulls or other item - it would make the plugin more efficient for servers with bad network.

**Comment by MrTigreroux** [comment]
Ok I will try to collect them asynchronously this week-end, thank you for the idea.

**Comment by MrTigreroux** [comment]
I tryed to collect the skulls asynchronously but I obtain a really unsatisfying code. The problem is that after collecting the skull, I have to check that the inventory is still opened, that it is correct, that the menu is still opened... I would clearly need to rethink the structure of the plugin to add this feature and I miss of time.
So I added the setting you suggested: [Config: CollectSkulls](https://github.com/MrTigreroux/TigerReports/blob/7a0bf7e392134f9f293437012b8e278b8055af9f/TigerReports/src/config.yml#L70-L71) in the new [version 4.9.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=299818). Maybe one day I will fix this issue.
