### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by 0x477564** [MrTigreroux/TigerReports#31]
Hi, I want to report a database error that occurs often in my server (it happened for like months).
If a player has a **long IP (?)** the update in the database does not occur, not inserting the report at all.

Print error message: https://hatebin.com/okqvrqdmio
No one can see the report (it only appears in chat): https://imgur.com/Vmks51F

**Comment by MrTigreroux** [comment]
Hello, as written in the [changelog of version 4.9.2](https://www.spigotmc.org/resources/tigerreports.25773/update?update=296679) of TigerReports, the type of the columns **'reporter_ip'** and **'reported_ip'** of table **'tigerreports_reports'** must be changed to **varchar(46)** because of the new IPs format.
Click [here](https://github.com/MrTigreroux/TigerReports/wiki/Change-type-of-'reporter_uuid'-(or-'reason')-column) to see how to do it (and adapt it with **'reporter_ip'** and **'reported_ip'** columns in place of 'reporter_uuid').
Assuming that you use the latest version of TigerReports, you also need to change the type of the column **'appreciation'** of table **'tigerreports_reports'** to **varchar(255)** (following the same instructions).
