### ISSUE TITLE
Report command exposes vanished players

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#33]
Running the "/report username" command is exposing vanished players. Reporting offline admin results in a message that says that you cannot report an offline player, while reporting an online vanished admin will send the report.

Steps to reproduce:
1. Log in on the server as a player
2. Try to report your second account while its offline
Observed: The message about not being able to report an offline player is sent
3. Log in using a second account with admin privileges
4. Enable vanish on your admin account
5. Try to report the admin account using your first account (this one without admin privileges)
Expected: The message about not being able to report an offline player should be sent
Observed: The report is sent successfully, so the player knows that this admin is online

**Comment by MrTigreroux** [comment]
Hello,
Can I ask you why users would be able to report admins ? If there is no reason for them, then consider giving the `tigerreports.report.exempt` permission to your admins. The (tab) suggestions of `/report` are not showing the exempted players, so the (vanished or not) admins wouldn't be displayed and wouldn't being able to be reported.
You would still obtain the "bad behaviour" but instead of the report sent, you would obtain the permission report error instead of the offline error that you expect. The problem is that I can't detect if a player is in vanish (as far as I know, because I imagine all vanish plugins doesn't work the same way). And that's not really logical to display the offline error message if the target is connected but has the `tigerreports.report.exempt` permission, except if this target is in vanish, which I cannot check.

**Comment by piotrskibapl** [comment]
I just added `tigerreports.report.exempt` for the staff, but as you mentioned it doesn't solve my problem - the message is still different when reporting an offline admin and when reporting a vanished admin.
This might be a problem on big servers like mine. I have ~70 players almost all the time during the day, and when some admin joins then all the players will know he's online because some player checked that using the "/report" command and sent a chat message about that.
What about using `player.canSee(anotherPlayer)`. I saw other plugins implementing this to check whether player is vanished or not and it looks to be working well.

**Comment by MrTigreroux** [comment]
Effectively, I never searched for this, I thought players were hidden via "forced"/"hidden" packets but Bukkit already implement it. Ok I will add it. Thank you for the help.

**Comment by MrTigreroux** [comment]
I still have a problem with admins that would be vanished on a server, but the reporter would be on a different server. I can't use canSee method throught servers. But if the admin is owning `tigerreports.report.exempt` permission, there is no problem for tab suggestions because he will not be shown in them. The problem still remains for `/report` command.
`ReportOnline` setting is meant to restrict reports to online players on the network and not only on the same Spigot server.
I don't know if you would want an option to restrict reports to same Spigot servers players.

**Comment by piotrskibapl** [comment]
Actually right now I am using this plugin on one server only, so I'm not sure how does it work when it's set up on multiple servers.
However, in my opinion, an option to restrict reports to the same Spigot servers players would be a good solution.

**Comment by MrTigreroux** [comment]
If you don't need it, I don't implement it for now, waiting for the request of another people.
Thank you for the suggestion, it has been added in new [version 4.11.5](https://www.spigotmc.org/resources/tigerreports.25773/update?update=355462).

**Comment by piotrskibapl** [comment]
Just checked and it works great. Thanks!
