### ISSUE TITLE
Plugins Translation Problems

### ISSUE THREAD

**Issue by Welnnys** [MrTigreroux/TigerReports#44]
Hello there, TigerReports and TigerReportsSupports keep getting back to French, I set both of them to English and I am using the pre configurated messages in the plugin pages, but they are still loading in French. I had them on English for certain amount of time ( before a few days for a few days ) but they are not loading properly for some reason. I don't have any kind of errors in the console. I will be more than happy if you help me out with that. Thanks in advance.

**Comment by MrTigreroux** [comment]
Hello,
In what version of Minecraft do your server run ?
In what format did you encode the messages.yml files ?
Did you try to restart your server (not just use `/reload` command) ?
Are you talking about the `Config: InfoLanguage` setting in config.yml which only concerns messages displayed in the console/logs ?

**Comment by Welnnys** [comment]
1. 1.8.8 ( Spigot )
2. I just copy and pasted the ones you have on the site ( EN )
3. I restarted my server several times, they were working a few days ago
4. Yes, I am talking about "Config: InfoLanguage"

**Comment by MrTigreroux** [comment]
You must encode the messages.yml file in **ANSI** because your server run a 1.8 Minecraft version.
You can use a software like Notepad++ to do so with the Encode tab at the top of the interface when you open the file.
Don't forget to save your file and then restart your server.
The `Config: InfoLanguage` setting doesn't change the ingame messages, only the messages of the console which you cannot change.

**Comment by Welnnys** [comment]
Thanks, the solution works perfectly fine. Appreciate the help. Hope you have an amazing day.

**Comment by MrTigreroux** [comment]
Nice, and thank you ! Hope the same for you :)
