### ISSUE TITLE
My server lags for 2 mins when start up

### ISSUE THREAD

**Issue by prozhong** [MrTigreroux/TigerReports#5]
Due to my server's poor network, the query will cause lag sometimes
Would you mind adding a config to ignore this query or make it async ?
Thank you !
https://github.com/MrTigreroux/TigerReports/blob/master/TigerReports/src/fr/mrtigreroux/tigerreports/managers/WebManager.java#L72

**Comment by MrTigreroux** [comment]
This query is only done at the server start and doesn't affect server performance after that.
It allows me to have some statistics on my plugin and to blacklist people if one day I had a problem with someone.
It's not possible that this query causes lags for 2 minutes on your server. The problem comes from another thing.

**Comment by prozhong** [comment]
maybe put it in an async task is a good idea

**Comment by MrTigreroux** [comment]
Ok I will do it but currently I don't have the time to update it. Expect it to be done in about 2 weeks.
Thank you for the help.

**Comment by MrTigreroux** [comment]
This query is now async in the [version 4.2](https://www.spigotmc.org/resources/tigerreports.25773/update?update=231189).
Thank you for the idea.
