### ISSUE TITLE
I don't think this is normal...

### ISSUE THREAD

**Issue by Fantom250YT** [MrTigreroux/TigerReports#51]
<img width="1475" alt="Screenshot 2021-02-01 at 17 22 41" src="https://user-images.githubusercontent.com/73852683/106494448-55b7d780-64b2-11eb-9164-a4fd6789382c.png">

**Comment by MrTigreroux** [comment]
Without any context it's hard for me to find where the problem comes. Do you use comments feature of reports and if so could you try to create a comment on a report and check if it trigger the lag spike ?
Does the lag spike comes when many players join your server ? Leave your server ? Send many messages ?

**Comment by MrTigreroux** [comment]
It should be fixed in new [version 4.12.1](https://www.spigotmc.org/resources/tigerreports.25773/update?update=388221). Thank you for reporting it.
