### ISSUE TITLE
Bug/Exploit

### ISSUE THREAD

**Issue by Odsodium** [MrTigreroux/TigerReports#62]
Hi there,
When testing tiger reports I notice that players can do /report [Player] and when they see the GUI, It allows them to shift click onto the items. Such as the barrier close block. It allows them to access many items.

**Comment by MrTigreroux** [comment]
This is not a bug induced by TigerReports but a bug induced by another plugin which manage (for no legitime reason) events in TigerReports GUIs. Try to disable all your plugins that have GUIs, then check that the exploit isn't anymore possible, then enable one by one the plugins you enabled to see which one introduce this exploit and contact the developer of this plugin in order to ask him to check that the inventories in which he manages events are inventories generated by his plugin.
