### ISSUE TITLE
¿Bug? UUids appear instead of names

### ISSUE THREAD

**Issue by Gonzamayo** [MrTigreroux/TigerReports#64]
In all the placeholders (_Staff_, _Player_, _Reported_, _Reporter_, etc) the UUIDs appear instead of the names of the players
![image](https://user-images.githubusercontent.com/40701080/118843180-3053ab80-b8a0-11eb-856e-b6b75aee1346.png)

**Comment by MrTigreroux** [comment]
Hello, what version of TigerReports do you use ? On what version of Spigot ? Is your server allowing cracked versions ? Can you try to restart your server and create a new report and check if the problem persists please ?
Do you have any error in the console/logs ? If so please copy/paste it here.

**Comment by Gonzamayo** [comment]
Hello, sorry for taking so long to answer.

The plugin version is 4.12.7
I am using Spigot 1.16.5
Allow cracked versions
Here is a log (At the time of reporting this ¿bug? I did not get these errors) https://pastebin.com/UV7i59qT

**Comment by MrTigreroux** [comment]
Could you try to install the plugin GroupManager please ? I just want to know if it will fix the issue with Vault.
In any case, you have Vault but the Chat feature of Vault doesn't seem to work on your server. Because of a mistake of mine, my code generate an error and prevents TigerReports to work correctly. I will fix it as soon as I can but I would like to know if GroupManager will fix the issue (you just have to stop your server, put the jar of GroupManager and restart your server and see if you still have UUIDs displayed in TigerReports GUIs).

**Comment by Gonzamayo** [comment]
¡Yes!
with GroupManager works, I don't know if it will also work with luckperms (which is the plugin that I will use in the future)
![image](https://user-images.githubusercontent.com/40701080/119021966-6e230380-b976-11eb-8354-1839fdd79ee9.png)

**Comment by MrTigreroux** [comment]
Ok so the problem is just because you have Vault but you haven't any plugin managing chat. Good to know. Will fix the issue as soon as possible, thank you for reporting it.

**Comment by Gonzamayo** [comment]
Thanks to you for this wonderful plugin.

**Comment by MrTigreroux** [comment]
Thank you for the compliment :)

**Comment by MrTigreroux** [comment]
I finally found the time to fix this issue in new [version 4.12.8](https://www.spigotmc.org/resources/tigerreports.25773/update?update=407158). Thank you again for reporting it.
