### ISSUE TITLE
add an option in config to change the report command from tigerreports:reports to /reports

### ISSUE THREAD

**Issue by EzWzs** [MrTigreroux/TigerReports#66]
some people cant run the first command when executing the reports so the plugin wont do anything because of protection plugins and yes i know you can maybe disable it with a whitelist of some sort but i havent found that and it would be more complicated then just adding a config option for it.

**Comment by MrTigreroux** [comment]
I don't know if you closed the issue because you found how to allow users to run `/tigerreports:report` command but in any case config options are for settings, in this case you don't want to change a feature behaviour but you just want to bypass the problem of another plugin.
Firstly, if one of your plugins prevents you from executing commands, there should have a way of allowing it. If not, consider using another plugin.
Secondly, there is no reason to prevent users from using the `/tigerreports:report` command, adding a setting in the config would incite the contrary. And it is a "soft credit" for my work to have the possibility to see that its my plugin TigerReports that is used on your server.

**Comment by EzWzs** [comment]
Hey yea i ended up finding out how to do it but my messages they show up french even though they are english and restart the server sitll nothing you say something about ansii encoding how do i do that i cant seem to find it

From Carlos i8

**Comment by EzWzs** [comment]
Also please pm me on discord EzWzs#3010
This mail crap is garbage

**Comment by MrTigreroux** [comment]
If you use Notepad++, you can click on the `Encode` tab at the top of the window and select ANSI if your server is on 1.8 or less, else select UTF-8 for higher versions of Minecraft. Then save your changes (`Ctrl` & `S` keys) and restart your server.
