### ISSUE TITLE
Suggestion: Add PlaceholderAPI support

### ISSUE THREAD

**Issue by iGabyTM** [MrTigreroux/TigerReports#8]
As the title say, would be cool to have some placeholders for this plugin, example:
`%tigerreports_reports_opened%` - Show the total amount of reports marked as `opened`
`%tigerreports_reports_total%` - Show the total amount of reports
`%tigerreports_reports_inprogress%` - Show the total amount of reports marked as `in progress`

**Comment by MrTigreroux** [comment]
I don't really see the interest of PlaceholderAPI (from a performance point of view), so I don't think I will add a support for it.
However, you can display the amount of in progress reports with the **_InProgress_** placeholder in [Messages: Reports-notification](https://github.com/MrTigreroux/TigerReports/blob/ea4039914f673ae830da3dae5598de411aaa59e4/TigerReports/messages/english.yml#L26) and do the same for every report status you want.

There is no "global" count for "opened" or total amount of reports because I didn't think it would interest anyone. In my opinion the more important is to know how many reports are waiting, but if you really want to have access to these informations, I could add a command to display them.

**Comment by LevM-A** [comment]
Just got the same questions, is there any placeholders from plugin that i can put into scoreboard?

**Comment by MrTigreroux** [comment]
No there is no global placeholders, only internal placeholders used by TigerReports for TigerReports. I personnaly don't see the particular need of displaying TigerReports data in a scoreboard.

**Comment by LevM-A** [comment]
well, in my case i need it to show the current opened reports in admin scoreboard, so that why i'm asking about Placeholders.

**Comment by MrTigreroux** [comment]
You can periodically send a notification to staff member (in the chat) about the amount of reports in each state (waiting, in process, ...) with [Config: Notifications: Staff](https://github.com/MrTigreroux/TigerReports/blob/35f674cb3eba3667a11d01578fb9841c25f29a68/TigerReports/src/config.yml#L82-L88) in config.yml file and [Messages: Reports-notification](https://github.com/MrTigreroux/TigerReports/blob/35f674cb3eba3667a11d01578fb9841c25f29a68/TigerReports/messages/english.yml#L28) in messages.yml.

**Comment by LevM-A** [comment]
Okay, got it. Thank you!
