### ISSUE TITLE
It would be nice to have the player's CPS in the report information

### ISSUE THREAD

**Issue by thiagogebrimm** [MrTigreroux/TigerReports#86]
I think after reporting a player could measure his CPS for a certain time (about 5 minutes) and record his CPS history in the report

It would be more complete on PvP servers and in general

**Comment by MrTigreroux** [comment]
You can already configure a command to execute after all reports with [Config: AutoCommands](https://github.com/MrTigreroux/TigerReports/blob/0764ed995f8750cad10f9f7f332c4def4de33ba0/TigerReports/src/config.yml#L39-L41) settings in config.yml.
That command could start a measure and at the end save the CPS in a comment of the report with `/reports comment <report id> <comment>` command.
I could add an option to save the CPS when the report is created, but that would require to constantly save all clicks of all players which could impact performances.
But in my opinion, that's more the role of an AntiCheat plugin to measure CPS and take decisions. If there is a moderator online, he could run a CPS check with another plugin and see if there is a problem or not. But here you would want that a TigerReports, a report plugin, saves the CPS of a player after a report. From my point of view, that's not the good thing to do. The best thing would be to run a CPS check from an AntiCheat plugin, the other good thing would be to give a CPS check command to moderators and they could run it after a report or without any report. But I don't see the point of saving in a report the CPS, because if a moderator is online he can check the CPS, if there is no moderator they would see the CPS in the report and wouldn't do anything more than comparing it to a value, which should be the role of an AntiCheat plugin.

**Comment by thiagogebrimm** [comment]
Can you tell me how I would do this command? Is there a way to put delay in autocommands?
And how would the CPS fit in the comment? In case mine is `/vulcan cps <player>` then the CPS comes out, how would I register the result in the comment?

**Comment by MrTigreroux** [comment]
You can create delayed commands with plugins like MyCommand. But I don't know a plugin that is able to pick data from messages in chat and execute a command with that data. That's not something difficult to do, but we usually use APIs instead of that.
What I suggest you is to find a plugin that checks CPS of players and alerts or punish players who cross a threshold, with or without a command given to players to check a specific player, but creating a report for that isn't necessary from my point of view.
